#!/bin/bash
clear
sleep 1

echo "##############################"
echo "#  Created By Mr 4n0nsr00t   #"
echo "#    Security Darknet        #"
echo "#     Santri Salafy Cyber    #"
echo "##############################"
echo "# 01 Server PHP Martabak SQL #"
echo "# 02 PHP Server              #"
echo "##############################"
sleep 1
read -p "Pilih_Nomor~#/ " n;


if [ $n = 01 ] || [ $n = 1 ];then
clear
pkg install php
clear
pkg install curl
curl -LO https://pastebin.com/raw/YWXp5HR7
mv YWXp5HR7 martabak.php
clear
echo "<=====[ Info ]=====>"
echo "Nama Server: 127.0.0.1:8080"
echo "Ketik CTRL+C untuk exit atau menghentikannya"
echo "<=====================================>"
php -S 127.0.0.1:8080 martabak.php

fi

if [ $n = 02 ] || [ $n = 2 ];then
clear
termux-setup-storage
echo "<=====[ Info ]=====>"
echo "Nama Server: 127.0.0.1:8080"
echo "Ketik CTRL+C untuk exit atau menghentikannya"
read -p "Tempat_Menyimpan~#/ " s;
read -p "Nama_File~#/ " f;
cd $s
php -S 127.0.0.1:8080 $f 
fi
